export default {
  // auth
  IS_LOADING: "IS_LOADING",
  LOGIN: "LOGIN",
  AUTENTICATED_SUCCESSFUL: "AUTENTICATED_SUCCESSFUL",
  //else
  SET_VALIDATION_ERROR: "SET_VALIDATION_ERROR",
  SET_NEW_EMPLOYEE_FORM_INPUT: "SET_NEW_EMPLOYEE_FORM_INPUT",
  SUBMIT_NEWEMPLOYEE_FORM: "SUBMIT_NEWEMPLOYEE_FORM",
  ALL_EMPLOYEES: "ALL_EMPLOYEES",
  EACH_WORKER: "EACH_WORKER",
  DELETE_WORKER: "DELETE_WORKER",
  // upload fileStore
  BEFORE_UPLOAD: "BEFORE_UPLOAD",
  ON_SCAN_REMOVE: "ON_SCAN_REMOVE",
  SET_UPLOAD: "SET_UPLOAD",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOADING_FAILED: "UPLOADING_FAILED",
  CLEAR_FILELIST: "CLEAR_FILELIST",
  // upload saga
  UPLOADS_SCANS_SC: "UPLOADS_SCANS_SC",
}
