export default {
    // auth
    IS_LOADING: "IS_LOADING",
    LOGIN: "LOGIN",
    AUTENTICATED_SUCCESSFUL: "AUTENTICATED_SUCCESSFUL",
    SET_VALIDATION_ERROR: "SET_VALIDATION_ERROR",
    SET_NEW_EMPLOYEE_FORM_INPUT: "SET_NEW_EMPLOYEE_FORM_INPUT",
}
