export default {
  // auth
  IS_LOADING: "IS_LOADING",
  LOGIN: "LOGIN",
  AUTENTICATED_SUCCESSFUL: "AUTENTICATED_SUCCESSFUL",
  SET_VALIDATION_ERROR: "SET_VALIDATION_ERROR",
  SET_NEW_EMPLOYEE_FORM_INPUT: "SET_NEW_EMPLOYEE_FORM_INPUT",
  SUBMIT_NEWEMPLOYEE_FORM: "SUBMIT_NEWEMPLOYEE_FORM",
  ALL_EMPLOYEES: "ALL_EMPLOYEES",
  EACH_WORKER: "EACH_WORKER",
  DELETE_WORKER: "DELETE_WORKER",
}
